### ISSUE TITLE
Descrizione

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/Rombo#1]
![es4_31_32](https://cloud.githubusercontent.com/assets/3002194/14734199/1b9227c2-0869-11e6-88ca-fc619c246283.jpg)

**Comment by lucifero55** [comment]
Non ho capito il 4.32. 
Dobbiamo chiedere di inserire un valore e se per esempio è 3 deve uscire così?
 *
***
 *

**Comment by FabioZTessitore** [comment]
Come al solito il codice è incasinato. Non puoi stampare gli asterischi uno alla volta per il numero giusto di volte come fanno tutti?
ps. riguardo al 4.32 se l'utente inserisce 3 deve uscire
```text
 *
***
 *
```

**Comment by lucifero55** [comment]
Il fatto che funzioni è già un passo avanti no? :P 
Ci lavorerò sopra

**Comment by lucifero55** [comment]
Può dirmi nello specifico cosa non le piace?

**Comment by FabioZTessitore** [comment]
te l'ho scritto, le stampe con due asterischi rendono incomprensibile il codice

**Comment by FabioZTessitore** [comment]
ok, va meglio. prosegui

**Comment by FabioZTessitore** [comment]
La logica utilizzata per le stampe (i cicli interni) continua ad essere poco chiara ... però funziona.
Prova a far scegliere all'utente il numero di righe da stampare e vediamo che succede

**Comment by lucifero55** [comment]
Posso farlo molto più semplice se mi impegno un po'
